---
title: "Likelihood examples"
author: "Casey O'Hara"
date: "1/7/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
set.seed(1234)

df1 <- data.frame(x = rnorm(n = 5, mean = 5, sd = 1))

p0 <- ggplot(df1, aes(x = x)) +
  geom_point(y = 0, color = 'blue', size = 2) +
  geom_hline(yintercept = 0, color = 'grey60', size = .5) +
  geom_vline(xintercept = 0, color = 'grey60', size = .5) +
  scale_x_continuous(limits = c(0, 10), breaks = seq(0, 10, 2), expand = c(0.01, 0.01)) +
  scale_y_continuous(limits = c(0, 0.4), expand = c(0.01, 0.01)) +
  theme_minimal() +
  theme(panel.grid.minor = element_blank()) +
  labs(x = 'mass (g)',
       y = 'probability density')
p0

p1 <- p0 + geom_vline(aes(xintercept = x), color = 'blue')

p1

p1 + 
  geom_function(fun = ~dnorm(.x, mean = 2), color = 'red', size = 1) +
  geom_point(aes(y = dnorm(x, mean = 2)), color = 'red', size = 2) +
  geom_vline(xintercept = 2, color = 'red', linetype = 'dashed', size = .25)
p1 + 
  geom_function(fun = ~dnorm(.x, mean = 2), color = 'black', alpha = .2, size = .25) +
  geom_function(fun = ~dnorm(.x, mean = 3.5), color = 'red', size = 1) +
  geom_point(aes(y = dnorm(x, mean = 3.5)), color = 'red', size = 2) +
  geom_vline(xintercept = 3.5, color = 'red', linetype = 'dashed', size = .25)

p1 + 
  geom_function(fun = ~dnorm(.x, mean = 2), color = 'black', alpha = .2, size = .25) +
  geom_function(fun = ~dnorm(.x, mean = 3.5), color = 'black', alpha = .2, size = .25) +
  geom_function(fun = ~dnorm(.x, mean = 5), color = 'red', size = 1) +
  geom_point(aes(y = dnorm(x, mean = 5)), color = 'red', size = 2) +
  geom_vline(xintercept = 5, color = 'red', linetype = 'dashed', size = .25)

p1 + 
  geom_function(fun = ~dnorm(.x, mean = 2), color = 'black', alpha = .2, size = .25) +
  geom_function(fun = ~dnorm(.x, mean = 3.5), color = 'black', alpha = .2, size = .25) +
  geom_function(fun = ~dnorm(.x, mean = 5), color = 'black', alpha = .2, size = .25) +
  geom_function(fun = ~dnorm(.x, mean = 6.5), color = 'red', size = 1) +
  geom_point(aes(y = dnorm(x, mean = 6.5)), color = 'red', size = 2) +
  geom_vline(xintercept = 6.5, color = 'red', linetype = 'dashed', size = .25)

x <- df1$x %>% sort()
pvec_2 <- dnorm(x, mean = 2); prod(pvec_2)
pvec_3.5 <- dnorm(x, mean = 3.5); prod(pvec_3.5)
pvec_5 <- dnorm(x, mean = 5); prod(pvec_5)
pvec_6.5 <- dnorm(x, mean = 6.5); prod(pvec_6.5)

```

